defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV.fetch('DB_USERNAME', 'ofn') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'f00d') %>

development:
  <<: *defaults
  database: open_food_network_dev

test:
  <<: *defaults
  database: open_food_network_test

production:
  <<: *defaults
  database: open_food_network_prod

staging:
  <<: *defaults
  database: open_food_network_prod
